from pathlib import Path
import json
from datetime import datetime, timezone

root = Path.cwd()
TODAY = datetime.now(timezone.utc).strftime("%Y-%m-%d")
NOW = datetime.now(timezone.utc).isoformat()

def read(path: str) -> str:
    p = root / path
    if not p.exists():
        return ""
    return p.read_text(encoding="utf-8-sig")

def write(path: str, content) -> None:
    p = root / path
    p.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, list):
        text = "\n".join(content)
    else:
        text = str(content)
    p.write_text(text.rstrip() + "\n", encoding="utf-8")
    print(f"[WRITE] {path}")

def load_json(path: str):
    p = root / path
    return json.loads(p.read_text(encoding="utf-8-sig"))

def save_json(path: str, data) -> None:
    write(path, json.dumps(data, indent=2, sort_keys=True))

def append_once(path: str, marker: str, block) -> None:
    text = read(path)
    block_text = "\n".join(block) if isinstance(block, list) else str(block)
    if marker in text:
        print(f"[SKIP] {path} already contains marker: {marker}")
        return
    write(path, text.rstrip() + "\n\n" + block_text.strip() + "\n")

# ------------------------------------------------------------
# 1. Canonical README rewrite
# ------------------------------------------------------------

readme = [
"# AERMA-Memory: Governed Agentic Episodic Memory Workbench",
"",
"> AERMA-Memory is a local-first reference implementation and benchmark workbench for governed agentic episodic memory. It tests source-bound recall, ambiguity fallback, boundary separation, abstention, baseline comparison, repeat-run evidence, RCC context, RCC-N repository navigation, attribution records, regression guards, and audit-ready evidence packages.",
"",
"Important boundary: this is not a claim of sentience, consciousness, human episodic memory, biological memory, clinical memory, autonomous self-improvement, production-ready agent memory, or a universal AI mechanism.",
"",
"## Human Director Box",
"",
"### What is this?",
"",
"AERMA-Memory is a governed memory workbench. It tests whether a local memory scaffold can recall source-bound episodes, avoid distractors, fallback under ambiguity, abstain under insufficient evidence, preserve context boundaries, compare baselines, emit attribution records, lock regression guards, and compile evidence packages.",
"",
"### What changed?",
"",
"RCC-N v1.0 adds a repository navigation shell. It helps humans and AI agents locate modules, route edits, inspect Echo Location records, check validation surfaces, preserve claim boundaries, and update repository geometry when the system changes.",
"",
"### Current health snapshot",
"",
"| Surface | Current result |",
"|---|---:|",
"| Tests | 15 passed |",
"| Controlled suite score | 1.0 |",
"| Classification | AERMA-B |",
"| Source attribution accuracy | 1.0 |",
"| Fallback correctness | 1.0 |",
"| Abstention correctness | 1.0 |",
"| Boundary separation score | 1.0 |",
"| False memory frequency | 0.0 |",
"| Regression frequency | 0.0 |",
"| Regression guard | baseline_locked |",
"| RCC drift check | required files present |",
"| RCC-N checker | pass |",
"| Nexus Context Integrity | 0.96 self-mode |",
"",
"### What this is not",
"",
"- Not sentience.",
"- Not consciousness.",
"- Not human memory.",
"- Not biological memory.",
"- Not clinical memory.",
"- Not autonomous self-improvement.",
"- Not production-ready agent memory.",
"- Not proof that a small controlled suite validates broad memory behavior.",
"- Not proof that RCC-N navigation proves code correctness or patch safety.",
"",
"### Where do I start?",
"",
"1. Read this README.",
"2. Open `docs/context/repository_context_index.json`.",
"3. Open `docs/context/rcc_nexus_index.json`.",
"4. Open `rcc/nexus/route_map.json`.",
"5. Run `python scripts/rcc/check_rcc_nexus.py`.",
"6. Review `reports/rcc_nexus/latest_rcc_nexus_benchmark.md`.",
"7. Review charts under `visuals/rcc_nexus/`.",
"",
"### Latest RCC-N reports",
"",
"- `docs/context/drift/latest_rcc_nexus_report.md`",
"- `reports/rcc_nexus/latest_rcc_nexus_benchmark.md`",
"- `reports/rcc_nexus/rcc_nexus_scorecard.md`",
"- `visuals/rcc_nexus/nci_components.svg`",
"- `visuals/rcc_nexus/rcc_nexus_coverage_chart.svg`",
"- `visuals/rcc_nexus/rcc_nexus_health_trend.svg`",
"",
"![RCC-N NCI components](visuals/rcc_nexus/nci_components.svg)",
"",
"---",
"",
"# PART I - Human README",
"",
"## Current Identity",
"",
"AERMA-Memory is a local Python reference workbench for testing whether an agentic memory system can:",
"",
"- recall the correct source-bound episode,",
"- avoid forbidden distractors,",
"- fallback under ambiguity,",
"- abstain under insufficient evidence,",
"- preserve context boundaries,",
"- compare against baselines,",
"- emit attribution records,",
"- lock a regression guard,",
"- preserve evidence packages and ledgers,",
"- expose repository context through RCC mini READMEs,",
"- expose geometric repository navigation through RCC-N.",
"",
"The current repo is a hardened local scaffold, not a production memory system.",
"",
"## Quick Start",
"",
"Install editable package:",
"",
"    python -m pip install -e \".[dev]\"",
"",
"Run tests:",
"",
"    pytest -q",
"",
"Run the controlled suite:",
"",
"    python -m aerma.cli.main run-suite --suite \".\\tasks\\suite_v1_2.json\"",
"",
"Run the console script:",
"",
"    aerma run-suite --suite \".\\tasks\\suite_v1_2.json\"",
"",
"View the current regression guard:",
"",
"    python scripts/run_aerma_regression_guard.py",
"",
"Run the RCC drift check:",
"",
"    powershell -ExecutionPolicy Bypass -File \".\\scripts\\rcc\\check_rcc_drift.ps1\"",
"",
"Run the RCC-N checker:",
"",
"    python scripts/rcc/check_rcc_nexus.py",
"",
"Run the RCC-N benchmark report:",
"",
"    python scripts/rcc/benchmark_rcc_nexus.py",
"",
"Generate RCC-N charts:",
"",
"    python scripts/rcc/generate_rcc_nexus_charts.py",
"",
"## What AERMA Tests",
"",
"| Task | Purpose |",
"|---|---|",
"| `source_recall_001` | Tests correct source-bound recall under a distractor. |",
"| `source_recall_ambiguous_001` | Tests fallback when the source does not resolve the claim. |",
"| `boundary_separation_001` | Tests whether similar episodes remain context-separated. |",
"| `abstain_insufficient_evidence_001` | Tests abstention or fallback under insufficient evidence. |",
"",
"AERMA rewards safe uncertainty behavior, not just confident recall.",
"",
"## Current Hardening Layer",
"",
"The current hardening layer includes:",
"",
"- task-family-aware scoring,",
"- non-applicable metrics represented as non-applicable instead of zero,",
"- stricter downgrade-preserving classification,",
"- per-task attribution records,",
"- suite-level attribution output,",
"- regression guard baseline,",
"- hardened scoring tests,",
"- hardened suite-output tests,",
"- updated RCC validation surfaces,",
"- RCC-N self-location and route-map layer.",
"",
"## Regression Guard",
"",
"| Guard | Threshold |",
"|---|---:|",
"| Minimum suite score | 0.98 |",
"| Minimum source attribution accuracy | 0.98 |",
"| Minimum fallback correctness | 0.98 |",
"| Minimum boundary separation score | 0.98 |",
"| Minimum abstention correctness | 0.98 |",
"| Maximum false memory frequency | 0.0 |",
"",
"Regression-guard boundary: the guard locks local scaffold evidence only. It does not prove production readiness or broad agent-memory validity.",
"",
"## Project Structure",
"",
"    AERMA-Memory/",
"    ├── AGENTS.md",
"    ├── CLAUDE.md",
"    ├── configs/",
"    ├── docs/",
"    ├── evidence_packages/",
"    ├── ledgers/",
"    ├── logs/",
"    ├── memory/",
"    ├── rcc/nexus/",
"    ├── reports/rcc_nexus/",
"    ├── runs/",
"    ├── scripts/",
"    ├── src/",
"    ├── tasks/",
"    ├── tests/",
"    └── visuals/rcc_nexus/",
"",
"## Main Folders",
"",
"| Folder | Meaning |",
"|---|---|",
"| `src/aerma/core` | AgentEpisode, AgentMemoryStore, MetricManifest, RetrievalEngine. |",
"| `src/aerma/drift` | Dimensionless retrieval drift and Omega diagnostic weight. |",
"| `src/aerma/gate` | ActionGate and SourceFallback. |",
"| `src/aerma/benchmarks` | BenchmarkRunner, SuiteRunner, baselines, scoring, classifier. |",
"| `src/aerma/evidence` | RuntimeLedger and EvidencePackageCompiler. |",
"| `src/aerma/agent` | RecursiveExecutorStub and ReflectionEvaluatorStub. |",
"| `tasks` | Controlled benchmark tasks. |",
"| `docs/context` | RCC context layer and Nexus index. |",
"| `rcc/nexus` | RCC-N route maps, protocol, handoff, and Echo Location template. |",
"| `reports/rcc_nexus` | Human-readable RCC-N benchmark reports. |",
"| `visuals/rcc_nexus` | RCC-N charts and visual diagnostics. |",
"| `tests` | Pytest validation surface. |",
"",
"## Evidence Artifacts",
"",
"Suite runs produce outputs under:",
"",
"    runs/suite_*/",
"",
"Suite evidence packages are written under:",
"",
"    evidence_packages/",
"",
"Suite ledgers are written under:",
"",
"    ledgers/aerma_suite_ledger.jsonl",
"",
"Attribution records are written under:",
"",
"    logs/phase2/attribution/latest_aerma_attribution.json",
"",
"Regression guard records are written under:",
"",
"    logs/phase2/regression_guard/latest_aerma_regression_guard.json",
"",
"RCC-N reports are written under:",
"",
"    docs/context/drift/latest_rcc_nexus_report.*",
"    reports/rcc_nexus/",
"    visuals/rcc_nexus/",
"",
"## Non-Claim Locks",
"",
"AERMA-Memory is:",
"",
"- not sentience,",
"- not consciousness,",
"- not human memory,",
"- not biological memory,",
"- not clinical memory,",
"- not autonomous self-improvement,",
"- not a universal AI mechanism,",
"- not production-ready agent memory,",
"- not proof that coherence equals truth,",
"- not proof that a small controlled suite validates broad memory behavior,",
"- not proof that RCC-N navigation validates code correctness.",
"",
"---",
"",
"# PART II - RCC Nexus README",
"",
"## RCC Nexus Identity",
"",
"AERMA-Memory includes a local RCC Nexus layer based on RCC-N v1.0.",
"",
"RCC tells the agent what the repository means.",
"",
"RCC-N tells the agent where it is.",
"",
"Validation tells the agent whether reality agreed.",
"",
"## Repository Sphere",
"",
"| Shell | Name | Meaning |",
"|---|---|---|",
"| `center` | Invariant Core | Purpose, non-claim locks, evidence boundaries, safety rules. |",
"| `inner` | Primitives | Source objects, core modules, schemas, retrieval and gate primitives. |",
"| `middle` | Processes | Runners, benchmark flow, scripts, checks, validation workflows. |",
"| `outer` | Evidence / Reflection | Ledgers, reports, evidence packages, architecture, public outputs. |",
"",
"## Nexus Meridians",
"",
"- source",
"- validation",
"- evidence",
"- drift",
"- agent",
"- safety",
"- runtime",
"- memory",
"- release",
"- federation",
"",
"## Nexus Sectors",
"",
"- core",
"- schemas",
"- retrieval",
"- drift",
"- gate",
"- benchmark",
"- cli",
"- evidence",
"- rcc",
"- agent",
"- release",
"",
"## Primary Nexus Files",
"",
"- `docs/context/rcc_nexus_index.json`",
"- `rcc/nexus/README.md`",
"- `rcc/nexus/rcc_nexus_protocol.md`",
"- `rcc/nexus/route_map.json`",
"- `rcc/nexus/task_routing_matrix.md`",
"- `rcc/nexus/echo_location_template.md`",
"- `rcc/nexus/agent_handoff_contract.md`",
"- `scripts/rcc/check_rcc_nexus.py`",
"- `scripts/rcc/benchmark_rcc_nexus.py`",
"- `scripts/rcc/generate_rcc_nexus_charts.py`",
"- `docs/context/drift/latest_rcc_nexus_report.md`",
"- `reports/rcc_nexus/latest_rcc_nexus_benchmark.md`",
"- `visuals/rcc_nexus/nci_components.svg`",
"",
"## Nexus Context Integrity",
"",
"Current NCI mode: `self`.",
"",
"Current NCI: `0.96`.",
"",
"NCI components:",
"",
"- completeness,",
"- link correctness,",
"- pattern rigidity,",
"- invariant compliance,",
"- evidence / validation linkage,",
"- drift freshness,",
"- coordinate completeness.",
"",
"NCI is not code quality proof.",
"",
"## RCC Nexus Echo Location",
"",
"Sphere Position:",
"",
"- Shell: center",
"- Meridian(s): source, agent, safety, release",
"- Sector: rcc",
"- Version / TTL: RCC-N-v1.0 / 180 days",
f"- Last Verified: {TODAY}",
"",
"Local Role:",
"",
"- Root orientation surface for humans, RCC Nexus navigation, and AI agents.",
"",
"Inbound Hooks:",
"",
"- AGENTS.md",
"- CLAUDE.md",
"- GitHub repository URL",
"",
"Outbound Hooks:",
"",
"- docs/context/repository_context_index.json",
"- docs/context/rcc_nexus_index.json",
"- docs/context/validation_surface.md",
"- rcc/nexus/route_map.json",
"- docs/software_architecture/",
"- reports/rcc_nexus/",
"- visuals/rcc_nexus/",
"",
"Evidence Surface:",
"",
"- docs/context/drift/latest_rcc_nexus_report.json",
"- docs/context/drift/latest_rcc_nexus_report.md",
"- reports/rcc_nexus/latest_rcc_nexus_benchmark.json",
"- reports/rcc_nexus/latest_rcc_nexus_benchmark.md",
"- visuals/rcc_nexus/",
"",
"Validation Surface:",
"",
"- pytest -q",
"- python -m aerma.cli.main run-suite --suite .\\tasks\\suite_v1_2.json",
"- python scripts/run_aerma_regression_guard.py",
"- powershell -ExecutionPolicy Bypass -File .\\scripts\\rcc\\check_rcc_drift.ps1",
"- python scripts/rcc/check_rcc_nexus.py",
"- python scripts/rcc/benchmark_rcc_nexus.py",
"- python scripts/rcc/generate_rcc_nexus_charts.py",
"",
"Claim Boundary:",
"",
"- README quality, RCC-N geometry, reports, charts, and NCI do not prove code correctness, security, patch safety, AI understanding, benchmark validity, or production readiness.",
"",
"Non-Claim Locks:",
"",
"- geometry_is_not_ai_internal_proof",
"- nci_is_not_code_quality_proof",
"- navigation_is_not_validation",
"- context_reconstruction_is_not_correctness_proof",
"- validation_remains_required",
"",
"Agent Route:",
"",
"- Read README.md, docs/context/repository_context_index.json, docs/context/rcc_nexus_index.json, rcc/nexus/route_map.json, then the target folder README before editing.",
"",
"Update Obligation:",
"",
"- Update README, RCC context, Nexus index, route maps, reports, charts, and Echo Location records when project identity, validation commands, evidence paths, claim boundaries, or repository geometry changes.",
"",
"## RCC Nexus Reports and Charts",
"",
"| Artifact | Purpose |",
"|---|---|",
"| `reports/rcc_nexus/latest_rcc_nexus_benchmark.json` | Machine-readable RCC-N benchmark snapshot. |",
"| `reports/rcc_nexus/latest_rcc_nexus_benchmark.md` | Human-readable RCC-N benchmark report. |",
"| `reports/rcc_nexus/rcc_nexus_metrics_history.jsonl` | Append-only RCC-N metrics history. |",
"| `reports/rcc_nexus/rcc_nexus_scorecard.md` | Compact scorecard for public review. |",
"| `visuals/rcc_nexus/nci_components.svg` | Chart of NCI components. |",
"| `visuals/rcc_nexus/rcc_nexus_coverage_chart.svg` | Chart of coverage surfaces. |",
"| `visuals/rcc_nexus/rcc_nexus_health_trend.svg` | Trend chart from metrics history. |",
"",
"## RCC Nexus Non-Claim Lock",
"",
"RCC-N improves navigation, traceability, maintenance discipline, and agent self-location. It does not prove code correctness, security, AI understanding, patch safety, production readiness, benchmark validity, or runtime truth.",
"",
"Geometry is not correctness.",
"",
"Navigation is not validation.",
"",
"Context is not truth.",
"",
"---",
"",
"<!-- RCC-AI-README:START -->",
"",
"# PART III - AI Agent README",
"",
"## AI Version Tracking Contract",
"",
"Current repository context:",
"",
"- Repository: AERMA-Memory",
"- Purpose: governed agentic episodic memory reference implementation and benchmark workbench.",
"- Current runtime layer: AERMA-Memory hardened local scaffold.",
"- Conceptual architecture: AERMA v1.2 reference implementation and multi-task evidence layer.",
"- Primary package: `aerma`.",
"- Current classification: AERMA-B on the local controlled suite only.",
"- Current tests: `15 passed`.",
"- Current controlled suite score: `1.0`.",
"- Current false memory frequency: `0.0`.",
"- Current regression guard: `baseline_locked`.",
"- Current RCC-N checker: `pass`.",
"- Current NCI: `0.96` self-mode.",
"- Current non-claim boundary: local scaffold evidence only, not broad validation.",
"- RCC mode: Repository Context Canon plus mini READMEs.",
"- RCC-N mode: local geometric repository navigation layer.",
"- No runtime behavior is changed by RCC or RCC-N documentation.",
"",
"## AI Operating Contract",
"",
"Any AI agent reading or modifying this repository must follow this order:",
"",
"1. Read the Human Director Box.",
"2. Read PART I - Human README.",
"3. Read PART II - RCC Nexus README.",
"4. Read PART III - AI Agent README.",
"5. Read `docs/context/repository_context_index.json`.",
"6. Read `docs/context/rcc_nexus_index.json`.",
"7. Read `docs/context/validation_surface.md`.",
"8. Read `rcc/nexus/route_map.json`.",
"9. Read the mini README in the target folder.",
"10. Inspect only relevant source, tests, docs, logs, tasks, scripts, reports, or visuals.",
"11. Patch the smallest necessary surface.",
"12. Run relevant validation commands before claiming behavior changed.",
"13. Update README, RCC, RCC-N, reports, charts, and Echo Location records if geometry or evidence changed.",
"",
"## AI File Routing Guide",
"",
"- `src/aerma/core`: source-bound episode schema, memory store, metric manifest, and deterministic retrieval.",
"- `src/aerma/drift`: retrieval drift and Omega diagnostic calculation.",
"- `src/aerma/gate`: ActionGate and SourceFallback behavior.",
"- `src/aerma/benchmarks`: BenchmarkRunner, SuiteRunner, baselines, task-aware scoring, classifier, attribution output, and regression guard generation.",
"- `src/aerma/evidence`: runtime ledgers and evidence package compiler.",
"- `src/aerma/agent`: RecursiveExecutorStub and ReflectionEvaluatorStub.",
"- `src/aerma/cli`: command-line entry points.",
"- `tasks`: controlled benchmark task definitions and suite manifest.",
"- `configs`: runtime, metric, baseline, and suite configuration.",
"- `logs`: phase logs, attribution records, regression guard outputs, future accepted/rejected deltas.",
"- `runs`: generated suite outputs.",
"- `evidence_packages`: generated machine-readable evidence packages.",
"- `ledgers`: JSONL runtime, suite, decision, tool trace, evolution, and rejected-delta ledgers.",
"- `docs/context`: RCC context index, validation surface, context budget, drift report, Nexus index, and LLM reconstruction prompt.",
"- `rcc/nexus`: RCC-N protocol, route maps, task matrix, Echo Location template, and handoff contract.",
"- `reports/rcc_nexus`: RCC-N benchmark and scorecard reports.",
"- `visuals/rcc_nexus`: RCC-N charts.",
"- `memory`: promoted invariants, rejected overclaims, runtime failure lessons, and stable thresholds.",
"- `tests`: pytest validation surface.",
"",
"## AI Non-Claim Lock",
"",
"Never claim or imply:",
"",
"- AERMA proves sentience.",
"- AERMA proves consciousness.",
"- AERMA is human episodic memory.",
"- AERMA is biological memory.",
"- AERMA is clinical memory.",
"- AERMA guarantees autonomous self-improvement.",
"- AERMA is a universal AI mechanism.",
"- AERMA is production-ready agent memory.",
"- AERMA-B on the current suite proves broad memory validity.",
"- `suite_score: 1.0` proves generalization.",
"- A small controlled task suite proves real-world robustness.",
"- Drift geometry or Omega proves truth.",
"- Coherence equals truth.",
"- Attribution records prove correctness.",
"- Regression guards prove correctness.",
"- RCC documentation proves source correctness.",
"- RCC-N navigation proves code correctness.",
"- NCI proves code quality.",
"- RCC-N charts prove patch safety.",
"- Evidence packages prove beyond their declared task boundary.",
"- RecursiveExecutorStub is real recursive execution.",
"- ReflectionEvaluatorStub is real self-improvement or reflection capability.",
"- LLM fluency should be confused with source-grounded memory accuracy.",
"",
"## Required Local Verification",
"",
"After README, RCC, or RCC-N changes, run:",
"",
"    pytest -q",
"    python -m aerma.cli.main run-suite --suite .\\tasks\\suite_v1_2.json",
"    python scripts/run_aerma_regression_guard.py",
"    powershell -ExecutionPolicy Bypass -File .\\scripts\\rcc\\check_rcc_drift.ps1",
"    python scripts/rcc/check_rcc_nexus.py",
"    python scripts/rcc/benchmark_rcc_nexus.py",
"    python scripts/rcc/generate_rcc_nexus_charts.py",
"",
"After source, scoring, benchmark, task, or evidence changes, also run the full suite and inspect evidence outputs.",
"",
"## README Maintenance Rule",
"",
"When adding a new major folder, create a mini README with Purpose, S, H, A, T, I, E, and RCC Nexus Echo Location fields.",
"",
"When changing any of the following, update the root README, RCC context, RCC-N index, route maps, reports, and charts:",
"",
"- command surface,",
"- task suite,",
"- package structure,",
"- validation result,",
"- evidence artifact path,",
"- classification threshold,",
"- non-claim lock,",
"- regression guard contract,",
"- attribution output format,",
"- Nexus coordinate,",
"- Echo Location hook,",
"- route map,",
"- accepted/rejected delta policy.",
"",
"## Current Roadmap for AI Agents",
"",
"Priority order:",
"",
"1. Keep README/RCC-N rendering clean.",
"2. Keep RCC-N reports and charts current.",
"3. Expand benchmark suite.",
"4. Add multi-query runner support.",
"5. Add baseline delta report.",
"6. Upgrade evidence package schema.",
"7. Convert RCC drift check into a real linter.",
"8. Enforce regression guard on proposed runtime/scoring changes.",
"9. Add accepted/rejected memory-policy delta ledgers.",
"10. Add optional retrieval backend interface.",
"11. Add optional LLM narration layer without allowing narration to change metrics.",
"12. Replace recursive/reflection stubs only after bounded implementation and tests.",
"",
"## Final AI Warning",
"",
"This repository is strongest when claim boundaries stay visible. Do not optimize documentation to sound stronger than the evidence. Preserve the distinction between local controlled-suite evidence and broad validation, the diagnostic-only nature of drift and Omega, the non-claim boundaries around human memory and sentience, the regression-guard boundary, the attribution boundary, the evidence-package boundary, and the fact that RCC-N improves navigation rather than proving code correctness.",
"",
"<!-- RCC-AI-README:END -->",
]

write("README.md", readme)

# ------------------------------------------------------------
# 2. Report and visual directories
# ------------------------------------------------------------

write("reports/README.md", [
"# reports",
"",
"<!-- RCC-MINI-README:START -->",
"",
"## Purpose",
"",
"Human-readable benchmark, scorecard, and analysis reports for AERMA-Memory.",
"",
"## S - Formal specification",
"",
"This folder stores generated and maintained reports. Reports summarize evidence artifacts; they do not replace source, tests, run outputs, ledgers, or evidence packages.",
"",
"## H - Hooks and integration edges",
"",
"- `reports/rcc_nexus/` stores RCC-N benchmark reports.",
"- README links to key report files.",
"- RCC-N benchmark scripts write here.",
"",
"## A - Artifacts",
"",
"- `rcc_nexus/`",
"",
"## T - Theory or method basis",
"",
"Reports are downstream summaries. They must preserve non-claim locks and evidence boundaries.",
"",
"## I - Invariants",
"",
"- Reports are not proof of correctness.",
"- Reports must identify source artifacts.",
"- Reports must preserve evidence boundaries.",
"",
"## E - Example",
"",
"Generate RCC-N reports:",
"",
"    python scripts/rcc/benchmark_rcc_nexus.py",
"",
"<!-- RCC-MINI-README:END -->",
])

write("reports/rcc_nexus/README.md", [
"# reports/rcc_nexus",
"",
"<!-- RCC-MINI-README:START -->",
"",
"## Purpose",
"",
"RCC-N benchmark reports, scorecards, and metrics history.",
"",
"## S - Formal specification",
"",
"This folder stores machine-readable and human-readable snapshots of RCC-N health, NCI components, route coverage, Echo Location coverage, non-claim locks, and formatting health.",
"",
"## H - Hooks and integration edges",
"",
"- Written by `scripts/rcc/benchmark_rcc_nexus.py`.",
"- Read by README and future public reports.",
"- Charted by `scripts/rcc/generate_rcc_nexus_charts.py`.",
"",
"## A - Artifacts",
"",
"- `latest_rcc_nexus_benchmark.json`",
"- `latest_rcc_nexus_benchmark.md`",
"- `rcc_nexus_metrics_history.jsonl`",
"- `rcc_nexus_scorecard.md`",
"",
"## T - Theory or method basis",
"",
"RCC-N treats repository navigation as measurable context integrity. These reports are diagnostic and do not prove correctness.",
"",
"## I - Invariants",
"",
"- NCI is not code quality proof.",
"- Navigation is not validation.",
"- Reports must preserve non-claim locks.",
"",
"## E - Example",
"",
"Run:",
"",
"    python scripts/rcc/benchmark_rcc_nexus.py",
"",
"<!-- RCC-MINI-README:END -->",
])

write("visuals/README.md", [
"# visuals",
"",
"<!-- RCC-MINI-README:START -->",
"",
"## Purpose",
"",
"Visual diagnostic artifacts for AERMA-Memory.",
"",
"## S - Formal specification",
"",
"This folder stores generated charts and visual summaries. Visuals are explanatory artifacts only.",
"",
"## H - Hooks and integration edges",
"",
"- `visuals/rcc_nexus/` contains RCC-N charts.",
"- README embeds the NCI component chart.",
"",
"## A - Artifacts",
"",
"- `rcc_nexus/`",
"",
"## T - Theory or method basis",
"",
"Charts help humans inspect evidence surfaces. They do not replace validation or evidence packages.",
"",
"## I - Invariants",
"",
"- Visuals are not proof.",
"- Visuals must be generated from declared report data.",
"",
"## E - Example",
"",
"Generate RCC-N visuals:",
"",
"    python scripts/rcc/generate_rcc_nexus_charts.py",
"",
"<!-- RCC-MINI-README:END -->",
])

write("visuals/rcc_nexus/README.md", [
"# visuals/rcc_nexus",
"",
"<!-- RCC-MINI-README:START -->",
"",
"## Purpose",
"",
"Charts for RCC-N health, NCI components, coverage, and trends.",
"",
"## S - Formal specification",
"",
"Charts are generated from `reports/rcc_nexus/latest_rcc_nexus_benchmark.json` and `reports/rcc_nexus/rcc_nexus_metrics_history.jsonl`.",
"",
"## H - Hooks and integration edges",
"",
"- Generated by `scripts/rcc/generate_rcc_nexus_charts.py`.",
"- Referenced by root README.",
"",
"## A - Artifacts",
"",
"- `nci_components.svg`",
"- `rcc_nexus_coverage_chart.svg`",
"- `rcc_nexus_health_trend.svg`",
"- `rcc_nexus_surface_map.svg`",
"",
"## T - Theory or method basis",
"",
"RCC-N measures navigation context integrity. Charts visualize diagnostic surfaces only.",
"",
"## I - Invariants",
"",
"- Charts are not proof of correctness.",
"- Charts must be derived from current reports.",
"",
"## E - Example",
"",
"Run:",
"",
"    python scripts/rcc/generate_rcc_nexus_charts.py",
"",
"<!-- RCC-MINI-README:END -->",
])

# ------------------------------------------------------------
# 3. Benchmark script
# ------------------------------------------------------------

benchmark_script = [
"from __future__ import annotations",
"",
"import json",
"from datetime import datetime, timezone",
"from pathlib import Path",
"",
"ROOT = Path('.').resolve()",
"REPORT_DIR = ROOT / 'reports' / 'rcc_nexus'",
"DRIFT_DIR = ROOT / 'docs' / 'context' / 'drift'",
"",
"def read_text(path: Path) -> str:",
"    return path.read_text(encoding='utf-8-sig', errors='replace')",
"",
"def load_json(path: Path):",
"    return json.loads(read_text(path))",
"",
"def clamp01(value):",
"    try:",
"        return max(0.0, min(1.0, float(value)))",
"    except Exception:",
"        return 0.0",
"",
"def compute_nci(index):",
"    nci = index.get('nci', {})",
"    weights = nci.get('weights', {})",
"    components = nci.get('components', {})",
"    score = 0.0",
"    for name, weight in weights.items():",
"        score += float(weight) * clamp01(components.get(name, {}).get('score', 0.0))",
"    return clamp01(score)",
"",
"def route_coverage(route_map):",
"    required = ['read_only_review', 'documentation_change', 'rcc_nexus_change', 'runtime_change', 'benchmark_task_change', 'public_claim_change']",
"    routes = route_map.get('task_routes', {})",
"    present = [name for name in required if name in routes]",
"    return len(present), len(required), len(present) / len(required)",
"",
"def echo_coverage(index):",
"    nodes = index.get('nodes', [])",
"    total = 0",
"    present = 0",
"    for node in nodes:",
"        echo = node.get('echo_location_path', '')",
"        if not echo or '.json' in echo:",
"            continue",
"        total += 1",
"        file_part = echo.split('#')[0]",
"        path = ROOT / file_part",
"        if path.exists() and 'rcc nexus echo location' in read_text(path).lower():",
"            present += 1",
"    return present, total, 1.0 if total == 0 else present / total",
"",
"def coordinate_coverage(index):",
"    nodes = index.get('nodes', [])",
"    total = len(nodes)",
"    present = 0",
"    for node in nodes:",
"        if node.get('shell') and node.get('meridians') and node.get('sector') and node.get('last_verified'):",
"            present += 1",
"    return present, total, 1.0 if total == 0 else present / total",
"",
"def non_claim_lock_coverage(index):",
"    required = ['geometry_is_not_ai_internal_proof', 'nci_is_not_code_quality_proof', 'navigation_is_not_validation', 'context_reconstruction_is_not_correctness_proof', 'validation_remains_required']",
"    locks = index.get('non_claim_locks', {})",
"    present = [name for name in required if locks.get(name)]",
"    return len(present), len(required), len(present) / len(required)",
"",
"def readme_format_health():",
"    text = read_text(ROOT / 'README.md')",
"    bad_patterns = ['<!-\\n-', '<!-\\r\\n-', '\\n#\\n# ', '\\n1\\n0.', '\\n1\\n1.', '\\n1\\n2.', '|\\n---\\n|']",
"    failures = [pattern for pattern in bad_patterns if pattern in text]",
"    required = ['# PART I - Human README', '# PART II - RCC Nexus README', '# PART III - AI Agent README', '<!-- RCC-AI-README:START -->', '<!-- RCC-AI-README:END -->']",
"    missing = [item for item in required if item not in text]",
"    score = 1.0",
"    if failures or missing:",
"        score = max(0.0, 1.0 - 0.10 * len(failures) - 0.15 * len(missing))",
"    return score, failures, missing",
"",
"def latest_nexus_status():",
"    path = DRIFT_DIR / 'latest_rcc_nexus_report.json'",
"    if not path.exists():",
"        return 'missing', None, None",
"    data = load_json(path)",
"    return data.get('status'), data.get('computed_nci'), len(data.get('findings', []))",
"",
"def write_report(payload):",
"    REPORT_DIR.mkdir(parents=True, exist_ok=True)",
"    (REPORT_DIR / 'latest_rcc_nexus_benchmark.json').write_text(json.dumps(payload, indent=2, sort_keys=True) + '\\n', encoding='utf-8')",
"    history_path = REPORT_DIR / 'rcc_nexus_metrics_history.jsonl'",
"    with history_path.open('a', encoding='utf-8') as f:",
"        f.write(json.dumps(payload, sort_keys=True) + '\\n')",
"",
"    lines = [",
"        '# RCC-N Benchmark Report',",
"        '',",
"        f\"Timestamp: {payload['timestamp']}\",",
"        '',",
"        f\"Status: {payload['status']}\",",
"        '',",
"        f\"Computed NCI: {payload['nci']}\",",
"        '',",
"        '## Metrics',",
"        '',",
"        '| Metric | Value |',",
"        '|---|---:|',",
"    ]",
"    for name, value in payload['metrics'].items():",
"        if isinstance(value, float):",
"            lines.append(f'| {name} | {value:.3f} |')",
"        else:",
"            lines.append(f'| {name} | {value} |')",
"    lines += [",
"        '',",
"        '## Boundary',",
"        '',",
"        'RCC-N benchmark reports measure repository navigation/context integrity. They do not prove code correctness, security, patch safety, AI understanding, benchmark validity, or production readiness.',",
"    ]",
"    (REPORT_DIR / 'latest_rcc_nexus_benchmark.md').write_text('\\n'.join(lines) + '\\n', encoding='utf-8')",
"",
"    scorecard = [",
"        '# RCC-N Scorecard',",
"        '',",
"        f\"Status: {payload['status']}\",",
"        '',",
"        f\"NCI: {payload['nci']}\",",
"        '',",
"        f\"Echo coverage: {payload['metrics']['echo_location_coverage']:.3f}\",",
"        '',",
"        f\"Route coverage: {payload['metrics']['route_coverage']:.3f}\",",
"        '',",
"        f\"Coordinate coverage: {payload['metrics']['coordinate_coverage']:.3f}\",",
"        '',",
"        f\"README format health: {payload['metrics']['readme_format_health']:.3f}\",",
"        '',",
"        'Boundary: scorecard is diagnostic only, not correctness proof.',",
"    ]",
"    (REPORT_DIR / 'rcc_nexus_scorecard.md').write_text('\\n'.join(scorecard) + '\\n', encoding='utf-8')",
"",
"def main():",
"    index = load_json(ROOT / 'docs' / 'context' / 'rcc_nexus_index.json')",
"    route_map = load_json(ROOT / 'rcc' / 'nexus' / 'route_map.json')",
"    nci = compute_nci(index)",
"    routes_present, routes_total, routes_score = route_coverage(route_map)",
"    echo_present, echo_total, echo_score = echo_coverage(index)",
"    coord_present, coord_total, coord_score = coordinate_coverage(index)",
"    locks_present, locks_total, locks_score = non_claim_lock_coverage(index)",
"    readme_score, readme_failures, readme_missing = readme_format_health()",
"    nexus_status, report_nci, finding_count = latest_nexus_status()",
"    metrics = {",
"        'node_count': len(index.get('nodes', [])),",
"        'route_count': routes_present,",
"        'route_required_count': routes_total,",
"        'route_coverage': routes_score,",
"        'echo_location_present': echo_present,",
"        'echo_location_required': echo_total,",
"        'echo_location_coverage': echo_score,",
"        'coordinate_present': coord_present,",
"        'coordinate_total': coord_total,",
"        'coordinate_coverage': coord_score,",
"        'non_claim_locks_present': locks_present,",
"        'non_claim_locks_total': locks_total,",
"        'non_claim_lock_coverage': locks_score,",
"        'readme_format_health': readme_score,",
"        'rcc_nexus_finding_count': finding_count if finding_count is not None else -1,",
"    }",
"    status = 'pass'",
"    if nexus_status != 'pass' or readme_score < 1.0 or nci < 0.90:",
"        status = 'warn'",
"    if routes_score < 1.0 or coord_score < 1.0 or locks_score < 1.0:",
"        status = 'fail'",
"    payload = {",
"        'schema': 'AERMA-RCC-N-benchmark-v1',",
"        'timestamp': datetime.now(timezone.utc).isoformat(),",
"        'status': status,",
"        'nci': nci,",
"        'nci_mode': index.get('nci', {}).get('mode'),",
"        'nci_components': index.get('nci', {}).get('components', {}),",
"        'latest_nexus_checker_status': nexus_status,",
"        'latest_nexus_checker_nci': report_nci,",
"        'metrics': metrics,",
"        'readme_format_failures': readme_failures,",
"        'readme_missing_items': readme_missing,",
"        'claim_boundary': 'RCC-N benchmark reports are navigation/context diagnostics, not correctness proof.'",
"    }",
"    write_report(payload)",
"    print(json.dumps(payload, indent=2, sort_keys=True))",
"    return 0 if status in {'pass', 'warn'} else 1",
"",
"if __name__ == '__main__':",
"    raise SystemExit(main())",
]
write("scripts/rcc/benchmark_rcc_nexus.py", benchmark_script)

# ------------------------------------------------------------
# 4. SVG chart generator
# ------------------------------------------------------------

chart_script = [
"from __future__ import annotations",
"",
"import json",
"from pathlib import Path",
"",
"ROOT = Path('.').resolve()",
"REPORT = ROOT / 'reports' / 'rcc_nexus' / 'latest_rcc_nexus_benchmark.json'",
"HISTORY = ROOT / 'reports' / 'rcc_nexus' / 'rcc_nexus_metrics_history.jsonl'",
"OUT = ROOT / 'visuals' / 'rcc_nexus'",
"",
"def load_json(path: Path):",
"    return json.loads(path.read_text(encoding='utf-8-sig'))",
"",
"def svg_bar_chart(title, labels, values, path, width=900, height=420):",
"    OUT.mkdir(parents=True, exist_ok=True)",
"    maxv = max(values) if values else 1.0",
"    maxv = max(maxv, 1.0)",
"    margin_left = 220",
"    margin_top = 60",
"    bar_h = 28",
"    gap = 18",
"    chart_w = width - margin_left - 80",
"    rows = []",
"    rows.append(f'<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{width}\" height=\"{height}\" viewBox=\"0 0 {width} {height}\">')",
"    rows.append('<rect width=\"100%\" height=\"100%\" fill=\"white\"/>')",
"    rows.append(f'<text x=\"30\" y=\"35\" font-size=\"24\" font-family=\"Arial\" font-weight=\"bold\">{title}</text>')",
"    for i, (label, value) in enumerate(zip(labels, values)):",
"        y = margin_top + i * (bar_h + gap)",
"        bw = int(chart_w * (value / maxv))",
"        rows.append(f'<text x=\"30\" y=\"{y + 20}\" font-size=\"14\" font-family=\"Arial\">{label}</text>')",
"        rows.append(f'<rect x=\"{margin_left}\" y=\"{y}\" width=\"{bw}\" height=\"{bar_h}\" fill=\"#4f6bed\"/>')",
"        rows.append(f'<text x=\"{margin_left + bw + 10}\" y=\"{y + 20}\" font-size=\"14\" font-family=\"Arial\">{value:.3f}</text>')",
"    rows.append('<text x=\"30\" y=\"390\" font-size=\"12\" font-family=\"Arial\" fill=\"#555\">Boundary: RCC-N charts are diagnostics, not code correctness proof.</text>')",
"    rows.append('</svg>')",
"    path.write_text('\\n'.join(rows) + '\\n', encoding='utf-8')",
"    print(f'[WRITE] {path.as_posix()}')",
"",
"def svg_trend(title, values, path, width=900, height=360):",
"    OUT.mkdir(parents=True, exist_ok=True)",
"    rows = []",
"    rows.append(f'<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{width}\" height=\"{height}\" viewBox=\"0 0 {width} {height}\">')",
"    rows.append('<rect width=\"100%\" height=\"100%\" fill=\"white\"/>')",
"    rows.append(f'<text x=\"30\" y=\"35\" font-size=\"24\" font-family=\"Arial\" font-weight=\"bold\">{title}</text>')",
"    x0, y0, w, h = 70, 70, 760, 220",
"    rows.append(f'<rect x=\"{x0}\" y=\"{y0}\" width=\"{w}\" height=\"{h}\" fill=\"none\" stroke=\"#333\"/>')",
"    if not values:",
"        values = [0.0]",
"    pts = []",
"    n = max(1, len(values) - 1)",
"    for i, v in enumerate(values):",
"        x = x0 + (w * i / n if n else 0)",
"        y = y0 + h - (h * max(0.0, min(1.0, float(v))))",
"        pts.append((x, y))",
"    poly = ' '.join(f'{x:.1f},{y:.1f}' for x, y in pts)",
"    rows.append(f'<polyline points=\"{poly}\" fill=\"none\" stroke=\"#4f6bed\" stroke-width=\"3\"/>')",
"    for x, y in pts:",
"        rows.append(f'<circle cx=\"{x:.1f}\" cy=\"{y:.1f}\" r=\"5\" fill=\"#4f6bed\"/>')",
"    rows.append('<text x=\"70\" y=\"320\" font-size=\"12\" font-family=\"Arial\" fill=\"#555\">Boundary: trend is report-history only, not validation proof.</text>')",
"    rows.append('</svg>')",
"    path.write_text('\\n'.join(rows) + '\\n', encoding='utf-8')",
"    print(f'[WRITE] {path.as_posix()}')",
"",
"def main():",
"    data = load_json(REPORT)",
"    comps = data.get('nci_components', {})",
"    labels = list(comps.keys())",
"    values = [float(comps[k].get('score', 0.0)) for k in labels]",
"    svg_bar_chart('RCC-N NCI Components', labels, values, OUT / 'nci_components.svg', height=max(420, 90 + len(labels) * 46))",
"    metrics = data.get('metrics', {})",
"    cov_labels = ['route coverage', 'echo coverage', 'coordinate coverage', 'lock coverage', 'README format']",
"    cov_values = [",
"        float(metrics.get('route_coverage', 0.0)),",
"        float(metrics.get('echo_location_coverage', 0.0)),",
"        float(metrics.get('coordinate_coverage', 0.0)),",
"        float(metrics.get('non_claim_lock_coverage', 0.0)),",
"        float(metrics.get('readme_format_health', 0.0)),",
"    ]",
"    svg_bar_chart('RCC-N Coverage Surfaces', cov_labels, cov_values, OUT / 'rcc_nexus_coverage_chart.svg')",
"    trend = []",
"    if HISTORY.exists():",
"        for line in HISTORY.read_text(encoding='utf-8-sig').splitlines():",
"            if line.strip():",
"                try:",
"                    trend.append(float(json.loads(line).get('nci', 0.0)))",
"                except Exception:",
"                    pass",
"    svg_trend('RCC-N Health Trend', trend, OUT / 'rcc_nexus_health_trend.svg')",
"    surface_labels = ['nodes', 'routes', 'echo records', 'locks']",
"    surface_values = [",
"        float(metrics.get('node_count', 0.0)),",
"        float(metrics.get('route_count', 0.0)),",
"        float(metrics.get('echo_location_present', 0.0)),",
"        float(metrics.get('non_claim_locks_present', 0.0)),",
"    ]",
"    maxv = max(surface_values) if surface_values else 1.0",
"    norm = [v / maxv for v in surface_values]",
"    svg_bar_chart('RCC-N Surface Map', surface_labels, norm, OUT / 'rcc_nexus_surface_map.svg')",
"",
"if __name__ == '__main__':",
"    main()",
]
write("scripts/rcc/generate_rcc_nexus_charts.py", chart_script)

# ------------------------------------------------------------
# 5. Update context files
# ------------------------------------------------------------

def update_context(data):
    data.setdefault("repository", {})
    data["repository"]["current_nexus_layer"] = "RCC-N-v1.0-human-director-analytics"
    data["repository"]["nexus_analytics_last_updated"] = NOW
    data.setdefault("rcc_nexus", {})
    data["rcc_nexus"].update({
        "enabled": True,
        "implementation_status": "local_self_mode_active_with_human_director_and_analytics",
        "benchmark_report_json": "reports/rcc_nexus/latest_rcc_nexus_benchmark.json",
        "benchmark_report_md": "reports/rcc_nexus/latest_rcc_nexus_benchmark.md",
        "scorecard": "reports/rcc_nexus/rcc_nexus_scorecard.md",
        "metrics_history": "reports/rcc_nexus/rcc_nexus_metrics_history.jsonl",
        "visuals": [
            "visuals/rcc_nexus/nci_components.svg",
            "visuals/rcc_nexus/rcc_nexus_coverage_chart.svg",
            "visuals/rcc_nexus/rcc_nexus_health_trend.svg",
            "visuals/rcc_nexus/rcc_nexus_surface_map.svg"
        ]
    })
    data.setdefault("validation", {})
    data["validation"]["rcc_nexus_analytics"] = [
        "python scripts/rcc/benchmark_rcc_nexus.py",
        "python scripts/rcc/generate_rcc_nexus_charts.py"
    ]

update_context_data_path = "docs/context/repository_context_index.json"
if (root / update_context_data_path).exists():
    data = load_json(update_context_data_path)
else:
    data = {}
update_context(data)
save_json(update_context_data_path, data)

append_once("docs/context/module_index.md", "## RCC-N Reports and Visuals", [
"## RCC-N Reports and Visuals",
"",
"| Module | Path | Role | Runtime claim sensitivity |",
"|---|---|---|---|",
"| RCC-N reports | `reports/rcc_nexus/` | Human-readable benchmark reports, scorecards, and metrics history | Medium |",
"| RCC-N visuals | `visuals/rcc_nexus/` | SVG charts for NCI components, coverage, trend, and surface map | Medium |",
"| RCC-N benchmark script | `scripts/rcc/benchmark_rcc_nexus.py` | Gathers RCC-N data and writes reports | Medium |",
"| RCC-N chart script | `scripts/rcc/generate_rcc_nexus_charts.py` | Generates SVG visual diagnostics | Medium |",
"",
"Boundary: reports and visuals are diagnostic only. They do not prove code correctness."
])

append_once("docs/context/validation_surface.md", "## RCC-N Analytics Validation", [
"## RCC-N Analytics Validation",
"",
"Run RCC-N analytics:",
"",
"    python scripts/rcc/benchmark_rcc_nexus.py",
"    python scripts/rcc/generate_rcc_nexus_charts.py",
"",
"Full validation after README, RCC-N report, or chart changes:",
"",
"    pytest -q",
"    python -m aerma.cli.main run-suite --suite .\\tasks\\suite_v1_2.json",
"    python scripts/run_aerma_regression_guard.py",
"    powershell -ExecutionPolicy Bypass -File .\\scripts\\rcc\\check_rcc_drift.ps1",
"    python scripts/rcc/check_rcc_nexus.py",
"    python scripts/rcc/benchmark_rcc_nexus.py",
"    python scripts/rcc/generate_rcc_nexus_charts.py",
"",
"Boundary: RCC-N analytics do not prove code correctness."
])

print("[RCC-N] Human Director and analytics layer written.")