from pathlib import Path
import json
from datetime import datetime, timezone

root = Path.cwd()

def write(path: str, lines):
    p = root / path
    p.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(lines, list):
        text = "\n".join(lines)
    else:
        text = str(lines)
    p.write_text(text.rstrip() + "\n", encoding="utf-8")
    print(f"[WRITE] {path}")

def read(path: str) -> str:
    p = root / path
    if not p.exists():
        return ""
    return p.read_text(encoding="utf-8-sig")

def append_once(path: str, marker: str, lines):
    text = read(path)
    block = "\n".join(lines) if isinstance(lines, list) else str(lines)
    if marker not in text:
        text = text.rstrip() + "\n\n" + block.strip() + "\n"
        write(path, text)
    else:
        print(f"[SKIP] {path} already contains marker: {marker}")

def update_json(path: str, updater):
    p = root / path
    if p.exists():
        data = json.loads(p.read_text(encoding="utf-8-sig"))
    else:
        data = {}
    updater(data)
    write(path, json.dumps(data, indent=2, sort_keys=True))

now = datetime.now(timezone.utc).isoformat()

# ------------------------------------------------------------
# docs/software_architecture/README.md update
# ------------------------------------------------------------

arch_readme_addition = [
    "",
    "## RCC-N v1.0 Nexus Architecture",
    "",
    "The RCC-N v1.0 architecture documents the next local integration layer for AERMA-Memory.",
    "",
    "Primary files:",
    "",
    "- `rcc_nexus_software_architecture_v1_0.md`",
    "- `rcc_nexus_implementation_contract_v1_0.md`",
    "",
    "Boundary:",
    "",
    "RCC-N improves repository navigation, agent self-location, Echo Location records, route maps, and Nexus Context Integrity. It does not prove code correctness, security, patch safety, model understanding, human memory, sentience, or production readiness."
]

if "rcc_nexus_software_architecture_v1_0.md" not in read("docs/software_architecture/README.md"):
    append_once("docs/software_architecture/README.md", "## RCC-N v1.0 Nexus Architecture", arch_readme_addition)

# ------------------------------------------------------------
# RCC-N software architecture document
# ------------------------------------------------------------

architecture = [
"# CODEX ΔΦ — RCC NEXUS SOFTWARE ARCHITECTURE (RCC-N v1.0)",
"",
"Geometric Repository Context Nexus and Spherical Echo Architecture for AERMA-Memory.",
"",
"## Version",
"",
"v1.0 — Geometric Repository Context Nexus · Locked · Human/RCC Nexus/AI README Trisection, Repository Sphere, Shell/Meridian/Sector Coordinates, Echo Location Records, Nexus Context Integrity, Navigation Entropy, Geometric Drift, Route Maps, and Validation-Bound AI Coding Protocols.",
"",
"## Author",
"",
"James Paul Jackson",
"",
"X / Twitter: @unifiedenergy11",
"",
"## Source / Author Attribution",
"",
"This software architecture is derived from and aligned with:",
"",
"- RCC v1.0 through RCC v1.3 repository context lineage.",
"- RCC-N v1.0 geometric repository-context Nexus theory.",
"- AERMA-Memory local RCC integration pattern.",
"- AERMA-RCC-ECHO v0.1.2 software architecture already locked in this repository.",
"- The user-originated Agent Echo Location / Spherical Echo insight.",
"",
"RCC-N v1.0 adds the missing geometric layer above RCC v1.3: Human/RCC Nexus/AI trisection, repository sphere, shell/meridian/sector coordinates, Echo Location records, route maps, Nexus Context Integrity, navigation entropy, geometric drift, and validation-bound AI coding protocol.",
"",
"## Date",
"",
"May 2026",
"",
"## Status",
"",
"CANONICAL SOFTWARE ARCHITECTURE LOCK — NOT FULL IMPLEMENTATION YET · NOT CODE CORRECTNESS · NOT PATCH SAFETY · NOT SECURITY · NOT AI UNDERSTANDING · NOT SENTIENCE · NOT HUMAN MEMORY · NOT BIOLOGICAL MEMORY · NOT CLINICAL MEMORY · NOT PRODUCTION READINESS.",
"",
"## Purpose",
"",
"Define how RCC-N v1.0 becomes a local, reproducible software layer inside AERMA-Memory.",
"",
"The goal is to make the repository self-locating:",
"",
"    repo URL",
"    -> Human README",
"    -> RCC Nexus README",
"    -> AI Agent README",
"    -> rcc_nexus_index.json",
"    -> route map",
"    -> local Echo Location record",
"    -> source / tests / evidence",
"    -> validation",
"    -> Nexus update",
"",
"## What This Is",
"",
"- A software architecture for local RCC-N integration.",
"- A repository-context navigation layer.",
"- A README trisection contract.",
"- A repository sphere model.",
"- A Shell / Meridian / Sector coordinate model.",
"- An Echo Location record standard.",
"- A route-map standard for AI-assisted coding.",
"- A Nexus Context Integrity scoring surface.",
"- A geometric drift and navigation-entropy framing.",
"- A validation-bound agent self-location protocol.",
"- A portability layer for future repos.",
"",
"## What This Is Not",
"",
"- Not a replacement for RCC v1.3.",
"- Not a replacement for AERMA runtime code.",
"- Not proof of repository correctness.",
"- Not proof that AI literally thinks in spheres.",
"- Not proof of model understanding.",
"- Not proof of patch safety.",
"- Not proof of security.",
"- Not permission to skip source inspection.",
"- Not permission to skip tests or evidence.",
"- Not permission to treat documentation as truth.",
"",
"## Core Extraction",
"",
"RCC-N v1.0 software invariant:",
"",
"    A repository becomes agent-locatable when human context, Nexus geometry, AI operating protocol, local Echo records, route maps, validation surfaces, evidence surfaces, and non-claim locks are exposed before modification begins.",
"",
"Operational law:",
"",
"    Safe agent action = RCI × NCI × validation pass × claim-boundary preservation.",
"",
"Implementation law:",
"",
"    No route, no safe patch.",
"    No Echo Location, no local context.",
"    No validation, no completion.",
"    No Nexus update review, no context-integrity claim.",
"",
"## Canonical Lock",
"",
"- RCC v1.3 remains the metric/evidence/TTL/linter base.",
"- RCC-N v1.0 is a geometric bridge layer.",
"- Repository geometry is external organization, not AI-internal proof.",
"- Human/RCC Nexus/AI README trisection is mandatory for mature use.",
"- Echo Location records must include position, hooks, evidence, validation, claim boundaries, agent route, and update obligation.",
"- NCI must disclose mode: self, linted, or verified.",
"- Navigation entropy and geometric drift are behavioral/structural metrics, not correctness proof.",
"- Validation remains the reality boundary.",
"- Evolutions must be additive unless a migration is explicitly documented.",
"",
"## README Trisection Contract",
"",
"A mature README is split into three layers:",
"",
"1. Human README",
"   - Purpose, quick start, status, installation, usage, repo structure, evidence boundary, roadmap.",
"",
"2. RCC Nexus README",
"   - Repository sphere, shell map, meridian map, sector map, Echo Location protocol, route maps, NCI, geometric drift, validation surfaces, evidence surfaces, non-claim locks.",
"",
"3. AI Agent README",
"   - Mandatory read order, task protocol, context budget, patch constraints, validation commands, done criteria, forbidden claims, update obligations.",
"",
"Rule:",
"",
"    RCC Nexus layer is the map.",
"    AI Agent layer is the operating protocol.",
"    They must not be fused.",
"",
"## Repository Sphere",
"",
"The repository sphere contains:",
"",
"- Center: invariant core, non-claim locks, safety boundaries, evidence-before-claim rules.",
"- Inner shell: primitives, source modules, schemas, core runtime objects.",
"- Middle shell: processes, runners, benchmarks, scripts, checks, workflows.",
"- Outer shell: evidence, ledgers, reports, architecture, public outputs.",
"",
"Every major indexed node receives coordinates:",
"",
"    coordinate(node) = shell + meridian + sector + version_or_TTL",
"",
"## Meridians",
"",
"Canonical meridians:",
"",
"- source",
"- validation",
"- evidence",
"- drift",
"- agent",
"- safety",
"- runtime",
"- memory",
"- release",
"- federation",
"",
"## Sectors",
"",
"Canonical sectors:",
"",
"- core",
"- schemas",
"- retrieval",
"- drift",
"- gate",
"- benchmark",
"- cli",
"- evidence",
"- rcc",
"- agent",
"- release",
"",
"## Echo Location Record",
"",
"Each major folder or module should expose:",
"",
"- Sphere Position",
"- Local Role",
"- Inbound Hooks",
"- Outbound Hooks",
"- Evidence Surface",
"- Validation Surface",
"- Claim Boundary",
"- Non-Claim Locks",
"- Agent Route",
"- Update Obligation",
"",
"## Route Map Contract",
"",
"The route map tells an agent what to read, where to inspect, what may be edited, what validations are required, and what RCC/Nexus records must be updated.",
"",
"Required task routes:",
"",
"- read_only_review",
"- documentation_change",
"- rcc_nexus_change",
"- runtime_change",
"- scoring_change",
"- benchmark_task_change",
"- evidence_change",
"- test_change",
"- public_claim_change",
"",
"## Nexus Context Integrity",
"",
"NCI measures geometric navigation integrity.",
"",
"Components:",
"",
"- completeness",
"- link correctness",
"- pattern rigidity",
"- invariant compliance",
"- evidence / validation linkage",
"- drift freshness",
"- coordinate completeness",
"",
"Default weighted form:",
"",
"    NCI = 0.15 completeness",
"        + 0.15 link correctness",
"        + 0.10 pattern rigidity",
"        + 0.20 invariant compliance",
"        + 0.15 evidence validation linkage",
"        + 0.10 drift freshness",
"        + 0.15 coordinate completeness",
"",
"Boundary:",
"",
"    NCI is not code quality proof.",
"",
"## Geometric Drift",
"",
"Geometric drift measures mismatch between the declared Nexus geometry and actual repo state.",
"",
"Drift components:",
"",
"- coordinate mismatch",
"- hook mismatch",
"- route-map mismatch",
"- evidence-surface mismatch",
"- validation-surface mismatch",
"- TTL/staleness mismatch",
"- claim-boundary mismatch",
"",
"## Agent Self-Location Protocol",
"",
"Before patching, an agent must:",
"",
"1. Identify task type.",
"2. Select context budget.",
"3. Read Human / RCC Nexus / AI layers.",
"4. Locate affected modules by shell, meridian, and sector.",
"5. Read Echo Location records.",
"6. Inspect source/tests/evidence.",
"7. Patch the smallest safe surface.",
"8. Run validation.",
"9. Update RCC/Nexus if geometry changed.",
"10. Downgrade unsupported claims.",
"",
"## Repository Implementation Target",
"",
"Target files for implementation:",
"",
"- README.md",
"- docs/context/rcc_nexus_index.json",
"- rcc/nexus/README.md",
"- rcc/nexus/rcc_nexus_protocol.md",
"- rcc/nexus/route_map.json",
"- rcc/nexus/task_routing_matrix.md",
"- rcc/nexus/echo_location_template.md",
"- rcc/nexus/agent_handoff_contract.md",
"- scripts/rcc/check_rcc_nexus.py",
"- docs/context/drift/latest_rcc_nexus_report.json",
"- docs/context/drift/latest_rcc_nexus_report.md",
"- major folder README Echo Location blocks",
"",
"## Validation Surface",
"",
"Architecture-only validation:",
"",
"    pytest -q",
"    python -m aerma.cli.main run-suite --suite .\\tasks\\suite_v1_2.json",
"    python scripts/run_aerma_regression_guard.py",
"    powershell -ExecutionPolicy Bypass -File .\\scripts\\rcc\\check_rcc_drift.ps1",
"",
"Implementation validation:",
"",
"    pytest -q",
"    python -m aerma.cli.main run-suite --suite .\\tasks\\suite_v1_2.json",
"    python scripts/run_aerma_regression_guard.py",
"    powershell -ExecutionPolicy Bypass -File .\\scripts\\rcc\\check_rcc_drift.ps1",
"    python scripts/rcc/check_rcc_nexus.py",
"",
"## Falsification Surface",
"",
"RCC-N use is invalid or downgraded if:",
"",
"- It replaces RCC v1.3 instead of extending it.",
"- It claims AI literally forms a sphere.",
"- It treats geometry as proof of understanding.",
"- It treats NCI as proof of code quality.",
"- It treats navigation as validation.",
"- It treats context reconstruction as correctness proof.",
"- README layers are fused.",
"- Echo Location records omit hooks, evidence, validation, or claim boundaries.",
"- Route maps are absent for patch/debug/refactor/benchmark tasks.",
"- AI instructions bypass Nexus routing.",
"- Stale coordinates are not disclosed.",
"- Source inspection is skipped for patch tasks.",
"- Validation is omitted while claiming completion.",
"",
"## Implementation Roadmap",
"",
"### Phase 1 — Architecture Lock",
"",
"- Add this architecture document.",
"- Add implementation contract.",
"- Reference both in README and context files.",
"- Validate runtime unchanged.",
"",
"### Phase 2 — Local Nexus Integration",
"",
"- Add README trisection.",
"- Add rcc/nexus folder.",
"- Add rcc_nexus_index.json.",
"- Add route map.",
"- Add Echo Location template.",
"- Add Nexus checker.",
"- Add reports.",
"- Add Echo Location blocks to major mini READMEs.",
"",
"### Phase 3 — Linted NCI",
"",
"- Convert self-reported NCI to linted NCI.",
"- Compute coverage and component scores.",
"- Emit pass/warn/fail reports.",
"",
"### Phase 4 — Portable RCC-N Injection",
"",
"- Add reusable templates.",
"- Add a script to inject RCC-N into another repo.",
"- Preserve repo-specific required-files and route-map config.",
"",
"## Public Framing",
"",
"RCC tells the agent what the repository means.",
"RCC-N tells the agent where it is.",
"Validation tells the agent whether reality agreed.",
"",
"## Concluding Compression",
"",
"RCC-N v1.0 turns repository context into navigation geometry.",
"",
"It does not prove correctness.",
"It does not prove AI understanding.",
"It does not prove patch safety.",
"",
"It improves orientation, routing, validation discipline, drift detection, claim-boundary preservation, and maintainability."
]

write("docs/software_architecture/rcc_nexus_software_architecture_v1_0.md", architecture)

# ------------------------------------------------------------
# RCC-N implementation contract
# ------------------------------------------------------------

implementation = [
"# RCC-N v1.0 Implementation Contract for AERMA-Memory",
"",
"## Purpose",
"",
"This contract defines the exact local implementation surfaces required to make RCC-N v1.0 real inside AERMA-Memory.",
"",
"## Implementation Mode",
"",
"Mode: local repository integration.",
"",
"Boundary: RCC-N improves repository navigation and context integrity. It does not change AERMA runtime behavior unless a later runtime pass explicitly does so.",
"",
"## Files to Add",
"",
"- `rcc/nexus/README.md`",
"- `rcc/nexus/rcc_nexus_protocol.md`",
"- `rcc/nexus/route_map.json`",
"- `rcc/nexus/task_routing_matrix.md`",
"- `rcc/nexus/echo_location_template.md`",
"- `rcc/nexus/agent_handoff_contract.md`",
"- `docs/context/rcc_nexus_index.json`",
"- `scripts/rcc/check_rcc_nexus.py`",
"- `docs/context/drift/latest_rcc_nexus_report.json`",
"- `docs/context/drift/latest_rcc_nexus_report.md`",
"",
"## Files to Update",
"",
"- `README.md`",
"- `docs/context/repository_context_index.json`",
"- `docs/context/module_index.md`",
"- `docs/context/validation_surface.md`",
"- major folder `README.md` files",
"",
"## README Change",
"",
"The root README must become a trisection:",
"",
"1. PART I - Human README",
"2. PART II - RCC Nexus README",
"3. PART III - AI Agent README",
"",
"## Required Nexus Index",
"",
"Canonical path:",
"",
"    docs/context/rcc_nexus_index.json",
"",
"Required top-level fields:",
"",
"- schema",
"- repository",
"- readme_trisection",
"- sphere",
"- nodes",
"- nci",
"- route_maps",
"- non_claim_locks",
"",
"## Required Major Nodes",
"",
"Initial AERMA nodes:",
"",
"- README.md",
"- docs/context",
"- docs/software_architecture",
"- src/aerma/core",
"- src/aerma/benchmarks",
"- src/aerma/evidence",
"- tasks",
"- tests",
"- logs",
"- runs",
"- evidence_packages",
"- ledgers",
"- scripts/rcc",
"- rcc/nexus",
"",
"## Echo Location Blocks",
"",
"Echo Location blocks should be added first to:",
"",
"- `docs/software_architecture/README.md`",
"- `docs/context/module_index.md` if appropriate",
"- `src/aerma/benchmarks/README.md`",
"- `src/aerma/evidence/README.md`",
"- `tasks/README.md`",
"- `tests/README.md`",
"- `scripts/README.md` or `scripts/rcc` documentation",
"- `rcc/nexus/README.md`",
"",
"## Nexus Checker Requirements",
"",
"The initial checker must validate:",
"",
"- root README trisection",
"- `docs/context/rcc_nexus_index.json` exists and parses",
"- required non-claim locks exist",
"- NCI mode is present",
"- NCI components are present",
"- required nodes have shell/meridian/sector",
"- route map exists",
"- Nexus report is emitted",
"",
"## Validation Commands",
"",
"Full validation after RCC-N implementation:",
"",
"    pytest -q",
"    python -m aerma.cli.main run-suite --suite .\\tasks\\suite_v1_2.json",
"    python scripts/run_aerma_regression_guard.py",
"    powershell -ExecutionPolicy Bypass -File .\\scripts\\rcc\\check_rcc_drift.ps1",
"    python scripts/rcc/check_rcc_nexus.py",
"",
"## Done Criteria",
"",
"RCC-N local integration is complete when:",
"",
"- README trisection exists.",
"- `docs/context/rcc_nexus_index.json` exists.",
"- `rcc/nexus/` exists.",
"- route map exists.",
"- at least key folders have Echo Location blocks.",
"- checker emits PASS or WARN with explicit non-claim boundary.",
"- validation commands pass.",
"- Git commit is clean.",
"",
"## Non-Claim Locks",
"",
"- Geometry is not correctness.",
"- Navigation is not validation.",
"- NCI is not code quality proof.",
"- Context reconstruction is not runtime truth.",
"- README quality is not benchmark evidence.",
"- RCC-N does not imply AI understanding.",
"",
"## Next Implementation Pass",
"",
"The next pass should implement this contract in one script. That script must avoid nested Markdown code fences inside the outer PowerShell block by using line arrays or plain indented code examples."
]

write("docs/software_architecture/rcc_nexus_implementation_contract_v1_0.md", implementation)

# ------------------------------------------------------------
# README update
# ------------------------------------------------------------

readme_block = [
"## RCC-N v1.0 Nexus Architecture",
"",
"AERMA-Memory now has an architecture lock for RCC Nexus local integration.",
"",
"Architecture documents:",
"",
"- `docs/software_architecture/rcc_nexus_software_architecture_v1_0.md`",
"- `docs/software_architecture/rcc_nexus_implementation_contract_v1_0.md`",
"",
"RCC-N v1.0 evolves the repository context layer from Human/AI readability into Human/RCC Nexus/AI trisection and geometric repository navigation.",
"",
"Implementation status:",
"",
"- Architecture: locked.",
"- Local implementation: next pass.",
"- Runtime behavior: unchanged by this architecture lock.",
"",
"Boundary:",
"",
"RCC-N improves agent navigation and repository-context integrity. It does not prove code correctness, security, patch safety, model understanding, or production readiness."
]

append_once("README.md", "## RCC-N v1.0 Nexus Architecture", readme_block)

# ------------------------------------------------------------
# docs/context/module_index.md update
# ------------------------------------------------------------

module_block = [
"## RCC-N Nexus Architecture Surface",
"",
"| Module | Path | Role | Runtime claim sensitivity |",
"|---|---|---|---|",
"| RCC-N software architecture | `docs/software_architecture/rcc_nexus_software_architecture_v1_0.md` | Defines Human/RCC Nexus/AI trisection, sphere, coordinates, Echo Location, route maps, NCI, and drift | Medium |",
"| RCC-N implementation contract | `docs/software_architecture/rcc_nexus_implementation_contract_v1_0.md` | Defines exact local implementation surfaces for RCC-N integration | Medium |",
"",
"Boundary: These documents lock implementation direction. They do not prove code correctness or runtime validity."
]

append_once("docs/context/module_index.md", "## RCC-N Nexus Architecture Surface", module_block)

# ------------------------------------------------------------
# docs/context/validation_surface.md update
# ------------------------------------------------------------

validation_block = [
"## RCC-N Architecture Validation",
"",
"Architecture-only RCC-N changes must preserve current runtime behavior.",
"",
"Required validation:",
"",
"    pytest -q",
"    python -m aerma.cli.main run-suite --suite .\\tasks\\suite_v1_2.json",
"    python scripts/run_aerma_regression_guard.py",
"    powershell -ExecutionPolicy Bypass -File .\\scripts\\rcc\\check_rcc_drift.ps1",
"",
"After implementation, also run:",
"",
"    python scripts/rcc/check_rcc_nexus.py",
"",
"Boundary: RCC-N architecture is not runtime proof."
]

append_once("docs/context/validation_surface.md", "## RCC-N Architecture Validation", validation_block)

# ------------------------------------------------------------
# repository_context_index update
# ------------------------------------------------------------

def update_index(data):
    data.setdefault("repository", {})
    data["repository"]["current_nexus_architecture_layer"] = "RCC-N-v1.0-architecture-lock"
    data["repository"]["nexus_architecture_last_updated"] = now

    data["rcc_nexus"] = {
        "enabled": False,
        "architecture_locked": True,
        "implementation_status": "planned_next_pass",
        "architecture_doc": "docs/software_architecture/rcc_nexus_software_architecture_v1_0.md",
        "implementation_contract": "docs/software_architecture/rcc_nexus_implementation_contract_v1_0.md",
        "planned_index": "docs/context/rcc_nexus_index.json",
        "planned_nexus_root": "rcc/nexus/",
        "planned_checker": "scripts/rcc/check_rcc_nexus.py",
        "claim_boundary": "RCC-N improves navigation and context integrity; it does not prove correctness."
    }

    data.setdefault("validation", {})
    data["validation"]["rcc_nexus_architecture"] = [
        "pytest -q",
        "python -m aerma.cli.main run-suite --suite .\\tasks\\suite_v1_2.json",
        "python scripts/run_aerma_regression_guard.py",
        "powershell -ExecutionPolicy Bypass -File .\\scripts\\rcc\\check_rcc_drift.ps1"
    ]

update_json("docs/context/repository_context_index.json", update_index)

print("[RCC-N] Architecture and implementation contract written.")